version: "3.6"

services:
  nginx:
    container_name: easysplit_nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./easysplit:/project
      - ./nginx/logs:/var/log/nginx
    networks:
      - easysplit_net

  backend:
    container_name: easysplit
    build: ./easysplit
    command: ./docker-entrypoint.sh
    restart: always
    env_file:
      - easysplit/.env
    depends_on:
      - mariadb
    volumes:
      - ./easysplit:/project
    networks:
      - easysplit_net

  mariadb:
    container_name: easysplit_mariadb
    image: mariadb:10.2.8
    # image: arm64v8/mariadb:latest
    restart: always
    env_file:
      - easysplit/.env
    ports:
      - "3306:3306"
    volumes:
      - easysplit:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - easysplit_net

  redis:
    container_name: easysplit_redis
    image: redis:alpine
    networks:
      - easysplit_net

volumes:
  easysplit:


networks:
  easysplit_net:
    driver: bridge
