version: "3.6"

services:

  backend:
    container_name: easysplit
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    volumes:
      - ./easysplit:/project
    networks:
      - easysplit_net

  mariadb:
    container_name: easysplit_mariadb
    image: mariadb:11.0.2
    # image: arm64v8/mariadb:11.0.2
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - easysplit:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - easysplit_net

  redis:
    container_name: easysplit_redis
    image: redis:alpine
    networks:
      - easysplit_net

volumes:
  easysplit:


networks:
  easysplit_net:
    driver: bridge
