# Generated by Django 4.0.4 on 2023-06-11 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=10)),
                ('currency', models.CharField(choices=[('TWD', 'TWD')], default='TWD', max_length=10)),
                ('exchange_rate', models.FloatField(default=1)),
                ('note', models.TextField(default='')),
                ('is_equal_split', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.FloatField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.member')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.FloatField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.member')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('currency', models.CharField(choices=[('TWD', 'TWD')], default='TWD', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='account.member')),
            ],
        ),
    ]
