# Generated by Django 4.0.4 on 2023-06-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('record', '0002_alter_record_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='from',
            old_name='amout',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='to',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='from',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.member'),
        ),
        migrations.AlterField(
            model_name='to',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.member'),
        ),
    ]
